name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Install ffmpeg development dependencies
      id: install_dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: ffremux-artifact
        path: ./ffremux

